version: "3"

services:
  landing:
    image: nginx:alpine
    container_name: kihearts-landing
    restart: unless-stopped
    volumes: 
      - ./landing-page:/usr/share/nginx/html
    networks:
      - app-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: kihearts-dashboard
    container_name: kihearts-dashboard
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/home/node/app
      - appdata:/home/node/app/storage
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- npm run dev

  db:
    image: mongo:4.1.8-xenial
    container_name: kihearts-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - dbdata:/data/db
    ports:
      - 8011:27017
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: kihearts-webserver
    restart: unless-stopped
    ports:
      - 8010:80
    volumes:
      - ./docker-compose/nginx/dev/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  appdata:
  node_modules:
