version: "3"

services:
  landing:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    image: kihearts-app-landing
    container_name: kihearts-app-landing
    restart: unless-stopped
    networks:
      - app-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: kihearts-app-dashboard
    container_name: kihearts-app-dashboard
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    volumes:
      - .:/home/node/app
      - appdata:/home/node/app/public
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- npm run pm2-start

  db:
    image: mongo:4.1.8-xenial
    container_name: kihearts-app-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: kihearts-app-webserver
    restart: unless-stopped
    ports:
      - 8011:80
      - 8012:433
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./docker-compose/certbot/conf:/etc/letsencrypt
      - ./docker-compose/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker-compose/certbot/conf:/etc/letsencrypt
      - ./docker-compose/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  appdata:
  node_modules:
